{{- if .Values.ngcCatalog.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ngcCatalog.secret.name }}
type: Opaque
stringData:
  NGC_NVCF_API_KEY: {{ .Values.ngcCatalog.secret.key | quote }}
  NGC_NVCF_ORG: {{ .Values.ngcCatalog.secret.org | quote }}
  {{- if .Values.ngcCatalog.secret.team }}
  NGC_NVCF_TEAM: {{ .Values.ngcCatalog.secret.team | quote }}
  {{- end }}
{{- end }}
