apiVersion: v2
appVersion: 1.16.0
dependencies:
  - name: opentelemetry-collector
    version: 0.138.*
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: metrics.enabled,traces.enabled
description: A Helm chart for Kubernetes to deploy cosmos-curate
name: cosmos-curate
type: application
version: 2.2.0
