resources:
  requests:
    cpu: "4"
    memory: "10Gi"
    nvidia.com/gpu: 1
  limits:
    cpu: "16"
    memory: "120Gi"
    nvidia.com/gpu: 1

metrics:
  enabled: false
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
imagePullSecret:
  create: true
  dockerConfigJson:
    registry: "nvcr.io"
    username: "$oauthtoken"
    password: "" # FILL_IN your NGC API key here, or provide on helm deploy with --set imagePullSecret.dockerConfigJson.password=${API_KEY}
image:
  pullPolicy: IfNotPresent
  repository: "nvcr.io/FILL_IN/cosmos-curate"
  tag: "FILL_IN"
ngcCatalog:
  secret:
    enabled: true
    name: "ngc-secret"
    key: ""  # FILL_IN your NGC API key here, or provide on helm deploy with --set ngcCatalog.secret.key=${MODEL_MANAGER_KEY}
    org: "FILL_IN"  # Set your NGC organization here
persistence:
  enabled: false
  storageClass: "fast-ssd"
  size: 800Gi
  retentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain  
